/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms.frames;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

/**
 *
 * @author HP
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        S_update = new javax.swing.JButton();
        S_search = new javax.swing.JButton();
        S_insert = new javax.swing.JButton();
        S_delete = new javax.swing.JButton();
        S_display = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        P_update = new javax.swing.JButton();
        P_search = new javax.swing.JButton();
        P_insert = new javax.swing.JButton();
        P_delete = new javax.swing.JButton();
        P_display = new javax.swing.JButton();
        O_search = new javax.swing.JButton();
        O_insert = new javax.swing.JButton();
        O_delete = new javax.swing.JButton();
        O_display = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        S_update.setText("Update");
        S_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S_updateActionPerformed(evt);
            }
        });

        S_search.setText("Search");
        S_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S_searchActionPerformed(evt);
            }
        });

        S_insert.setText("Insert");
        S_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S_insertActionPerformed(evt);
            }
        });

        S_delete.setText("Delete");
        S_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S_deleteActionPerformed(evt);
            }
        });

        S_display.setText("Display");
        S_display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S_displayActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setText("PARTS");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setText("ORDERS");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setText("SUPPLIERS");

        P_update.setText("Update");
        P_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_updateActionPerformed(evt);
            }
        });

        P_search.setText("Search");
        P_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_searchActionPerformed(evt);
            }
        });

        P_insert.setText("Insert");
        P_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_insertActionPerformed(evt);
            }
        });

        P_delete.setText("Delete");
        P_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_deleteActionPerformed(evt);
            }
        });

        P_display.setText("Display");
        P_display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_displayActionPerformed(evt);
            }
        });

        O_search.setText("Search");
        O_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                O_searchActionPerformed(evt);
            }
        });

        O_insert.setText("New");
        O_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                O_insertActionPerformed(evt);
            }
        });

        O_delete.setText("Cancel");
        O_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                O_deleteActionPerformed(evt);
            }
        });

        O_display.setText("Display all");
        O_display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                O_displayActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(S_search, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(S_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(S_update)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(S_delete)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(S_display))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(O_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(P_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(19, 19, 19)
                                            .addComponent(O_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(O_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(O_display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(P_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(P_update)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(P_delete)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(P_display)))))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(S_search)
                    .addComponent(S_insert)
                    .addComponent(S_update)
                    .addComponent(S_delete)
                    .addComponent(S_display))
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P_search)
                    .addComponent(P_insert)
                    .addComponent(P_update)
                    .addComponent(P_delete)
                    .addComponent(P_display))
                .addGap(37, 37, 37)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(O_search)
                    .addComponent(O_insert)
                    .addComponent(O_delete)
                    .addComponent(O_display))
                .addGap(33, 33, 33)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void S_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S_searchActionPerformed
        this.setVisible(false);
        SupSearch supSearchObj = new SupSearch();
        supSearchObj.setVisible(true);
    }//GEN-LAST:event_S_searchActionPerformed

    private void S_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S_updateActionPerformed
        this.setVisible(false);
        SupUpdate supUpdateObj = new SupUpdate();
        supUpdateObj.setVisible(true);
    }//GEN-LAST:event_S_updateActionPerformed

    private void S_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S_insertActionPerformed
        this.setVisible(false);
        SupInsert supInsertObj = new SupInsert();
        supInsertObj.setVisible(true);
    }//GEN-LAST:event_S_insertActionPerformed

    private void S_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S_deleteActionPerformed
        this.setVisible(false);
        SupDelete supDeleteObj = new SupDelete();
        supDeleteObj.setVisible(true);
    }//GEN-LAST:event_S_deleteActionPerformed

    private void P_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_updateActionPerformed
        this.setVisible(false);
        ParUpdate parUpdateObj = new ParUpdate();
        parUpdateObj.setVisible(true);
    }//GEN-LAST:event_P_updateActionPerformed

    private void P_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_searchActionPerformed
        this.setVisible(false);
        ParSearch parSearchObj = new ParSearch();
        parSearchObj.setVisible(true);
    }//GEN-LAST:event_P_searchActionPerformed

    private void P_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_insertActionPerformed
        this.setVisible(false);
        ParInsert parInsertObj = new ParInsert();
        parInsertObj.setVisible(true);
    }//GEN-LAST:event_P_insertActionPerformed

    private void P_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_deleteActionPerformed
        this.setVisible(false);
        ParDelete parDeleteObj = new ParDelete();
        parDeleteObj.setVisible(true);
    }//GEN-LAST:event_P_deleteActionPerformed

    private void O_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_O_searchActionPerformed
        this.setVisible(false);
        OrdSearch ordSearchObj = new OrdSearch();
        ordSearchObj.setVisible(true);
    }//GEN-LAST:event_O_searchActionPerformed

    private void O_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_O_insertActionPerformed
        this.setVisible(false);
        OrdInsert ordInsertObj = new OrdInsert();
        ordInsertObj.setVisible(true);
    }//GEN-LAST:event_O_insertActionPerformed

    private void O_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_O_deleteActionPerformed
        this.setVisible(false);
        OrdDelete ordDeleteObj = new OrdDelete();
        ordDeleteObj.setVisible(true);
    }//GEN-LAST:event_O_deleteActionPerformed

    private void S_displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S_displayActionPerformed
        this.setVisible(false);
        SupDisplay supDisplayObj = new SupDisplay();
        supDisplayObj.setVisible(true);
    }//GEN-LAST:event_S_displayActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void P_displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_displayActionPerformed
        this.setVisible(false);
        ParDisplay parDisplayObj = new ParDisplay();
        parDisplayObj.setVisible(true);
    }//GEN-LAST:event_P_displayActionPerformed

    private void O_displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_O_displayActionPerformed
        this.setVisible(false);
        OrdDisplay ordDisplayObj = new OrdDisplay();
        ordDisplayObj.setVisible(true);
    }//GEN-LAST:event_O_displayActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton O_delete;
    private javax.swing.JButton O_display;
    private javax.swing.JButton O_insert;
    private javax.swing.JButton O_search;
    private javax.swing.JButton P_delete;
    private javax.swing.JButton P_display;
    private javax.swing.JButton P_insert;
    private javax.swing.JButton P_search;
    private javax.swing.JButton P_update;
    private javax.swing.JButton S_delete;
    private javax.swing.JButton S_display;
    private javax.swing.JButton S_insert;
    private javax.swing.JButton S_search;
    private javax.swing.JButton S_update;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
